services:
  postgres-db:
    image: postgres:16-alpine
    container_name: fintrack_postgres
    environment:
      POSTGRES_DB: fintrack_db
      POSTGRES_USER: fintrack_admin
      POSTGRES_PASSWORD: fintrack_secure_pass_2026
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fintrack_admin -d fintrack_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fintrack-network


  backend-api:
    build:
      context: ./backend/enterprise-backend
      dockerfile: Dockerfile
    container_name: fintrack_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/fintrack_db
      - SPRING_DATASOURCE_USERNAME=fintrack_admin
      - SPRING_DATASOURCE_PASSWORD=fintrack_secure_pass_2026
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - fintrack-network

  frontend-client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fintrack_frontend
    ports:
      - "80:80"
    depends_on:
      - backend-api
    networks:
      - fintrack-network

networks:
  fintrack-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local